### ISSUE TITLE
Inconsistent emphasis between highlighting and rendered forms

### ISSUE THREAD

**Issue by cptroot** [joemccann/dillinger#229]
If you type something that looks like `a_b_c_`
The editor will highlight the `_b_` part, but the preview displays `b_c` as italicized.

**Comment by benjamin-albert** [comment]
I cannot reproduce this on dillinger.io

I'm guessing this was resolved when we switched to `markdown-it`.

**Comment by cptroot** [comment]
I'm still seeing this on Chrome 50.0.2661.94 (64-bit). If I type `_a_b_c_d_`, then I see a and c as highlighted italic, while a_b_c_d is italicized in the preview.
